# github webhook test line 2
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: ${PUID}:${PGID}
    networks:
      - media-network
    dns: 192.168.5.76
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_CACHE}:/cache
      - ${MEDIA_LOCATION}:/data
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
    environment:
      - TZ=${TIMEZONE}
      - UMASK=002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.serbicki.com`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=traefik-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.local.serbicki.com`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=letsencrypt"

  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${JELLYSEERR_CONFIG}:/app/config
    ports:
      - ${JELLYSEERR_PORT}:5055
    environment:
      - TZ=${TIMEZONE}
    networks:
      - media-network

networks:
  media-network:
    external: true
