services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    networks:
      - media-network
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - ${MEDIA_LOCATION}:/media
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
    environment:
      - TZ=${TIMEZONE}

networks:
  media-network:
    external: true
